apiVersion: v1
kind: Service
metadata:
  name: {{ include "qasic.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: qasic-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: qasic-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
