apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qasic.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: qasic-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: qasic-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qasic-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
