{{- if and .Values.postgres.enabled .Values.postgres.useExternalSecret .Values.postgres.externalSecret.secretStoreRef .Values.postgres.externalSecret.remoteRef.secretName .Values.postgres.externalSecret.targetSecretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "qasic.fullname" . }}-postgres
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.postgres.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.postgres.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.postgres.externalSecret.remoteRef.secretName }}
        {{- if .Values.postgres.externalSecret.remoteRef.key }}
        property: {{ .Values.postgres.externalSecret.remoteRef.key }}
        {{- end }}
{{- end }}
