# QASIC Engineering-as-Code: OpenTofu IaC
# - local: run full stack via Docker Compose (Redis, Postgres, InfluxDB, MLflow, API, Celery, frontend)
# - aws: create RDS + ElastiCache (and optionally ECS) for cloud deployment

# --- Local: generate env file and run docker compose ---

resource "local_file" "env_tofu" {
  count    = var.deployment_target == "local" ? 1 : 0
  content  = <<-EOT
# Generated by OpenTofu - do not edit by hand
INFLUX_TOKEN=${var.influx_token}
EOT
  filename = "${local.root}/.env.tofu"
}

resource "null_resource" "compose_up" {
  count = var.deployment_target == "local" ? 1 : 0

  triggers = {
    compose_file = local.compose_path
    env_content  = local_file.env_tofu[0].content
  }

  provisioner "local-exec" {
    command     = "docker compose -f ${local.compose_path} --env-file ${local.root}/.env.tofu up -d --build"
    working_dir = local.root
    interpreter = ["sh", "-c"]
    on_failure  = fail
  }

  provisioner "local-exec" {
    when       = destroy
    command    = "docker compose -f ${local.compose_path} down"
    working_dir = local.root
    interpreter = ["sh", "-c"]
    on_failure = continue
  }

  depends_on = [local_file.env_tofu]
}

# --- AWS: RDS + ElastiCache (when deployment_target = "aws") ---

module "aws_networking" {
  count  = var.deployment_target == "aws" ? 1 : 0
  source = "./modules/aws_networking"

  project_name = var.aws_project_name
  region       = var.aws_region
}

module "aws_data" {
  count  = var.deployment_target == "aws" ? 1 : 0
  source = "./modules/aws_data"

  project_name             = var.aws_project_name
  region                   = var.aws_region
  vpc_id                   = module.aws_networking[0].vpc_id
  private_subnet_ids       = module.aws_networking[0].private_subnet_ids
  data_security_group_id   = module.aws_networking[0].data_security_group_id
  db_username              = var.db_username
  db_password              = coalesce(var.db_password, "changeme-${var.aws_project_name}")
  create_rds               = var.create_aws_rds
  create_elasticache       = var.create_aws_elasticache
}
